-- MySQL schema for Pyferium Produtos API
-- Database: mydb_local

CREATE DATABASE IF NOT EXISTS `mydb_local`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;

USE `mydb_local`;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `GEN_PRODUTO`;
DROP TABLE IF EXISTS `GEN_CATEGORIA`;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `GEN_CATEGORIA` (
  `CODCATEGORIA` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador interno da categoria.',
  `DSCCATEGORIA` varchar(45) NOT NULL COMMENT 'Descrição da categoria.',
  `CODNIVEL` varchar(2) NOT NULL COMMENT 'Nível da categoria.',
  `IDTATIVO` char(1) NOT NULL DEFAULT 'S' COMMENT 'Status lógico da categoria.',

  PRIMARY KEY (`CODCATEGORIA`),

  UNIQUE KEY `UQ_GEN_CATEGORIA_DSCCATEGORIA` (`DSCCATEGORIA`),

  CONSTRAINT `CK_GEN_CATEGORIA_IDTATIVO`
    CHECK (`IDTATIVO` IN ('S', 'N'))
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Categorias de produto.';

CREATE TABLE `GEN_PRODUTO` (
  `CODPRODUTO` int NOT NULL AUTO_INCREMENT COMMENT 'Identificador interno do produto.',
  `NOMPRODUTO` varchar(80) NOT NULL COMMENT 'Nome do produto.',
  `CODCATEGORIA` int NOT NULL COMMENT 'Categoria do produto.',
  `VLRPRODUTO` decimal(10,2) NOT NULL COMMENT 'Valor atual do produto.',
  `IDTATIVO` char(1) NOT NULL DEFAULT 'S' COMMENT 'Status lógico do produto.',

  PRIMARY KEY (`CODPRODUTO`),

  UNIQUE KEY `UQ_GEN_PRODUTO_CATEGORIA_NOME` (`CODCATEGORIA`, `NOMPRODUTO`),
  KEY `IDX_GEN_PRODUTO_CODCATEGORIA` (`CODCATEGORIA`),

  CONSTRAINT `FK_GEN_PRODUTO_CATEGORIA`
    FOREIGN KEY (`CODCATEGORIA`)
    REFERENCES `GEN_CATEGORIA` (`CODCATEGORIA`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT `CK_GEN_PRODUTO_IDTATIVO`
    CHECK (`IDTATIVO` IN ('S', 'N')),

  CONSTRAINT `CK_GEN_PRODUTO_VLRPRODUTO`
    CHECK (`VLRPRODUTO` > 0)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Cadastro de produtos.';