<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Aplicacao\**" />
		<Compile Remove="Dominio\**" />
		<Compile Remove="Infraestrutura\**" />
		<Content Remove="Aplicacao\**" />
		<Content Remove="Dominio\**" />
		<Content Remove="Infraestrutura\**" />
		<EmbeddedResource Remove="Aplicacao\**" />
		<EmbeddedResource Remove="Dominio\**" />
		<EmbeddedResource Remove="Infraestrutura\**" />
		<None Remove="Aplicacao\**" />
		<None Remove="Dominio\**" />
		<None Remove="Infraestrutura\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.79" />
		<PackageReference Include="FluentNHibernate" Version="3.4.1" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
		<PackageReference Include="NHibernate" Version="5.6.1" />
		<PackageReference Include="NHibernate.Driver.MySqlConnector" Version="2.0.5" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Pyferium.Produtos.Aplicacao\Pyferium.Produtos.Aplicacao.csproj" />
		<ProjectReference Include="..\Pyferium.Produtos.Infraestrutura\Pyferium.Produtos.Infraestrutura.csproj" />
	</ItemGroup>

</Project>
